=== Drilonpacarizi/SocialNetwork/Pika 9/SocialNetwork.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT SocialNetwork1 ANY>
<!ELEMENT SocialNetwork (UserGroup+, Users+, Posts+, Followings+, Comments+, Messages+, Likes+, Verejtje+, Bllok+, HyrjeDalje+, Shitja*)>
<!ELEMENT UserGroup (Prioriteti1) >
<!ATTLIST UserGroup
	Prioriteti ID #REQUIRED
>
<!ELEMENT Prioriteti1 (#PCDATA)>

<!ELEMENT Users (email, username, password, emri, mbiemri, gjinia, qyteti, shteti, Data_e_lindjes, Mosha, Data_e_krijimit)>
<!ATTLIST Users
	user_id ID #REQUIRED
	Prioriteti IDREF #REQUIRED
>
<!ELEMENT email (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT emri (#PCDATA)>
<!ELEMENT mbiemri (#PCDATA)>
<!ELEMENT gjinia (#PCDATA)>
<!ELEMENT qyteti (#PCDATA)>
<!ELEMENT shteti (#PCDATA)>
<!ELEMENT Data_e_lindjes (#PCDATA)>
<!ELEMENT Mosha (#PCDATA)>
<!ELEMENT Data_e_krijimit (#PCDATA)>
<!ELEMENT Posts (Pershkrimi, Lloji, Data_e_krijimit1)>
<!ATTLIST Posts
	post_id ID #REQUIRED
	user_id IDREF #REQUIRED
>
<!ELEMENT Pershkrimi (#PCDATA)>
<!ELEMENT Lloji (#PCDATA)>
<!ELEMENT Data_e_krijimit1 (#PCDATA)>
<!ELEMENT Followings (Date)>
<!ATTLIST Followings
	user_id IDREF #REQUIRED
	following_id IDREF #REQUIRED
>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Comments (Permbajtja, Data_e_komentimit, Data_e_ndryshimit)>
<!ATTLIST Comments
	comment_id ID #REQUIRED
	post_id IDREF #REQUIRED
	user_id IDREF #REQUIRED
>
<!ELEMENT Permbajtja (#PCDATA)>
<!ELEMENT Data_e_komentimit (#PCDATA)>
<!ELEMENT Data_e_ndryshimit (#PCDATA)>
<!ELEMENT Messages (texti, Data_e_dergimit, ora_e_leximit)>
<!ATTLIST Messages
	message_id ID #REQUIRED
	user_id_from IDREF #REQUIRED
	user_id_to IDREF #REQUIRED
>
<!ELEMENT texti (#PCDATA)>
<!ELEMENT Data_e_dergimit (#PCDATA)>
<!ELEMENT ora_e_leximit (#PCDATA)>
<!ELEMENT Likes (koha_e_liket)>
<!ATTLIST Likes
	likes_id ID #REQUIRED
	user_id IDREF #REQUIRED
	post_id IDREF #REQUIRED
>
<!ELEMENT koha_e_liket (#PCDATA)>
<!ELEMENT Verejtje (data, Pershkrimi1)>
<!ATTLIST Verejtje
	IDVerejtja ID #REQUIRED
	user_from IDREF #REQUIRED
	user_to IDREF #REQUIRED
>
<!ELEMENT data (#PCDATA)>
<!ELEMENT Pershkrimi1 (#PCDATA)>


<!ELEMENT Bllok ( Data, Arsyeja)>
<!ATTLIST Bllok
	IDBllok ID #REQUIRED
	user_from IDREF #REQUIRED
	user_to IDREF #REQUIRED
>
<!ELEMENT Data (#PCDATA)>
<!ELEMENT Arsyeja (#PCDATA)>


<!ELEMENT HyrjeDalje ( Logout, Login)>
<!ATTLIST HyrjeDalje
	IDHyrjeDalje ID #REQUIRED
	username IDREF #REQUIRED
>
<!ELEMENT Logout (#PCDATA)>
<!ELEMENT Login (#PCDATA)>


<!ELEMENT Shitja ( Koha , Produkti)>
<!ATTLIST Shitja 
	 user_ID  ID #REQUIRED
	 add_ID CDATA #REQUIRED
	 Username IDREF #REQUIRED>
<!ELEMENT Koha (#PCDATA)>
<!ELEMENT Produkti (#PCDATA)>

=== Drilonpacarizi/SocialNetwork/Pika 9/SocialNetwork.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SocialNetwork1 SYSTEM "C:\Users\Flamur Jahiri\Desktop\SocialNetwork.dtd">
<SocialNetwork1>
	<SocialNetwork>
	
		<UserGroup Prioriteti="A1">
			<Prioriteti1>USER</Prioriteti1>
		</UserGroup>
		<UserGroup Prioriteti="A2">
			<Prioriteti1>ADMIN</Prioriteti1>
		</UserGroup>
		
		
		<Users Prioriteti="A2" user_id="B1">
			<email>jahiriflamur@gmail.com</email>
			<username>flamurjahiri</username>
			<password>123456</password>
			<emri>Flamur</emri>
			<mbiemri>Jahiri</mbiemri>
			<gjinia>M</gjinia>
			<qyteti>Pr</qyteti>
			<shteti>Kosove</shteti>
			<Data_e_lindjes>18.08.1999</Data_e_lindjes>
			<Mosha>19</Mosha>
			<Data_e_krijimit>1.10.2019</Data_e_krijimit>
		</Users>
		<Users Prioriteti="A2" user_id="B2">
			<email>drilonpacarizi@gmail.com</email>
			<username>drilonpacarizi</username>
			<password>123456</password>
			<emri>Drilon</emri>
			<mbiemri>Pacarizi</mbiemri>
			<gjinia>M</gjinia>
			<qyteti>Pr</qyteti>
			<shteti>Kosove</shteti>
			<Data_e_lindjes>15.03.1999</Data_e_lindjes>
			<Mosha>19</Mosha>
			<Data_e_krijimit>2.10.2019</Data_e_krijimit>
		</Users>
		<Users Prioriteti="A1" user_id="B3">
			<email>ardikrasniqi@gmail.com</email>
			<username>ardikrasniqi</username>
			<password>123456</password>
			<emri>Ardi</emri>
			<mbiemri>Krasniqi</mbiemri>
			<gjinia>M</gjinia>
			<qyteti>Terpeze e poshtme</qyteti>
			<shteti>Kosove</shteti>
			<Data_e_lindjes>20.07.1999</Data_e_lindjes>
			<Mosha>19</Mosha>
			<Data_e_krijimit>3.10.2019</Data_e_krijimit>
		</Users>
		<Users Prioriteti="A1" user_id="B4">
			<email>trimmuharremi@gmail.com</email>
			<username>trimmuharremi</username>
			<password>123456</password>
			<emri>Trim</emri>
			<mbiemri>Muharremi</mbiemri>
			<gjinia>M</gjinia>
			<qyteti>Ferizaj</qyteti>
			<shteti>Kosove</shteti>
			<Data_e_lindjes>15.01.1999</Data_e_lindjes>
			<Mosha>19</Mosha>
			<Data_e_krijimit>4.10.2019</Data_e_krijimit>
		</Users>
		<Users Prioriteti="A1" user_id="B5">
			<email>vullkantopanica@gmail.com</email>
			<username>vullkantopanica</username>
			<password>123456</password>
			<emri>Flamur</emri>
			<mbiemri>Jahiri</mbiemri>
			<gjinia>M</gjinia>
			<qyteti>Pr</qyteti>
			<shteti>Kosove</shteti>
			<Data_e_lindjes>23.02.1998</Data_e_lindjes>
			<Mosha>19</Mosha>
			<Data_e_krijimit>5.10.2019</Data_e_krijimit>
		</Users>
		<Users Prioriteti="A1" user_id="B6">
			<email>mn@gmail.com</email>
			<username>mn</username>
			<password>123456</password>
			<emri>Mark</emri>
			<mbiemri>Ndrecaj</mbiemri>
			<gjinia>M</gjinia>
			<qyteti>Kline</qyteti>
			<shteti>Kosove</shteti>
			<Data_e_lindjes>18.01.1999</Data_e_lindjes>
			<Mosha>19</Mosha>
			<Data_e_krijimit>6.10.2019</Data_e_krijimit>
		</Users>
		<Users Prioriteti="A1" user_id="B7">
			<email>ab@gmail.com</email>
			<username>antigonab</username>
			<password>123456</password>
			<emri>Antigona</emri>
			<mbiemri>Bajraktari</mbiemri>
			<gjinia>F</gjinia>
			<qyteti>Pr</qyteti>
			<shteti>Kosove</shteti>
			<Data_e_lindjes>23.09.1999</Data_e_lindjes>
			<Mosha>19</Mosha>
			<Data_e_krijimit>7.10.2019</Data_e_krijimit>
		</Users>
		<Users Prioriteti="A1" user_id="B8">
			<email>tringa-t@gmail.com</email>
			<username>tringatahiri</username>
			<password>123456</password>
			<emri>Tringa</emri>
			<mbiemri>Tahiri</mbiemri>
			<gjinia>F</gjinia>
			<qyteti>Peje</qyteti>
			<shteti>Kosove</shteti>
			<Data_e_lindjes>20.10.1999</Data_e_lindjes>
			<Mosha>19</Mosha>
			<Data_e_krijimit>8.10.2019</Data_e_krijimit>
		</Users>
		<Users Prioriteti="A1" user_id="B9">
			<email>teuta_jonuzi@gmail.com</email>
			<username>teuta123</username>
			<password>123456</password>
			<emri>Teuta</emri>
			<mbiemri>Jonuzi</mbiemri>
			<gjinia>F</gjinia>
			<qyteti>Mitrovice</qyteti>
			<shteti>Kosove</shteti>
			<Data_e_lindjes>19.07.1999</Data_e_lindjes>
			<Mosha>19</Mosha>
			<Data_e_krijimit>9.10.2019</Data_e_krijimit>
		</Users>
		<Users Prioriteti="A1" user_id="B10">
			<email>magbuljasw@gmail.com</email>
			<username>magbulja</username>
			<password>123456</password>
			<emri>Magbule</emri>
			<mbiemri>Hajdari</mbiemri>
			<gjinia>F</gjinia>
			<qyteti>Kuks</qyteti>
			<shteti>Shqiperi</shteti>
			<Data_e_lindjes>23.11.1999</Data_e_lindjes>
			<Mosha>19</Mosha>
			<Data_e_krijimit>10.10.2019</Data_e_krijimit>
		</Users>
		
		
		<Posts post_id="P1" user_id="B1">
			<Pershkrimi>Fotografia e pare</Pershkrimi>
			<Lloji>foto</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>
		<Posts post_id="P2" user_id="B5">
			<Pershkrimi>video e pare</Pershkrimi>
			<Lloji>video</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>
		<Posts post_id="P3" user_id="B7">
			<Pershkrimi>Video e pare</Pershkrimi>
			<Lloji>video</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>
		<Posts post_id="P4" user_id="B6">
			<Pershkrimi>Fotografia e pare</Pershkrimi>
			<Lloji>foto</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>
		<Posts post_id="P5" user_id="B6">
			<Pershkrimi>Fotografia e dyte</Pershkrimi>
			<Lloji>foto</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>
		<Posts post_id="P6" user_id="B1">
			<Pershkrimi>Texti i pare</Pershkrimi>
			<Lloji>text</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>
		<Posts post_id="P7" user_id="B1">
			<Pershkrimi>Texti i dyte</Pershkrimi>
			<Lloji>text</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>
		<Posts post_id="P8" user_id="B1">
			<Pershkrimi>Texti i trete</Pershkrimi>
			<Lloji>text</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>
		<Posts post_id="P9" user_id="B2">
			<Pershkrimi>Video e pare</Pershkrimi>
			<Lloji>video</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>
		<Posts post_id="P10" user_id="B5">
			<Pershkrimi>foto e pare</Pershkrimi>
			<Lloji>foto</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>
		<Posts post_id="P11" user_id="B5">
			<Pershkrimi>texti i pare</Pershkrimi>
			<Lloji>text</Lloji>
			<Data_e_krijimit1>03.09.2016</Data_e_krijimit1>
		</Posts>


		<Followings user_id="B1" following_id="B2">
			<Date>18.08.2019</Date>
		</Followings>
		<Followings user_id="B4" following_id="B2">
			<Date>20.08.2019</Date>
		</Followings>
		<Followings user_id="B1" following_id="B6">
			<Date>21.08.2019</Date>
		</Followings>
		<Followings user_id="B6" following_id="B1">
			<Date>12.09.2019</Date>
		</Followings>
		<Followings user_id="B3" following_id="B4">
			<Date>11.08.2019</Date>
		</Followings>
		<Followings user_id="B4" following_id="B5">
			<Date>17.06.2019</Date>
		</Followings>
		<Followings user_id="B2" following_id="B7">
			<Date>12.01.2019</Date>
		</Followings>
		<Followings user_id="B1" following_id="B2">
			<Date>18.07.2019</Date>
		</Followings>
		<Followings user_id="B8" following_id="B2">
			<Date>15.03.2019</Date>
		</Followings>
		<Followings user_id="B7" following_id="B6">
			<Date>17.01.2019</Date>
		</Followings>
		
		
		<Comments post_id="P1" user_id="B1" comment_id="C1">
			<Permbajtja>testi</Permbajtja>
			<Data_e_komentimit>22.08.2018</Data_e_komentimit>
			<Data_e_ndryshimit>17.01.2019</Data_e_ndryshimit>
		</Comments>
		<Comments post_id="P2" user_id="B1" comment_id="C2">
			<Permbajtja>testi</Permbajtja>
			<Data_e_komentimit>30.08.2018</Data_e_komentimit>
			<Data_e_ndryshimit>01.01.2019</Data_e_ndryshimit>
		</Comments>
		<Comments post_id="P2" user_id="B1" comment_id="C3">
			<Permbajtja>testi</Permbajtja>
			<Data_e_komentimit>14.08.2018</Data_e_komentimit>
			<Data_e_ndryshimit>12.01.2019</Data_e_ndryshimit>
		</Comments>
		<Comments post_id="P4" user_id="B5" comment_id="C4">
			<Permbajtja>testi</Permbajtja>
			<Data_e_komentimit>15.09.2018</Data_e_komentimit>
			<Data_e_ndryshimit>01.01.2019</Data_e_ndryshimit>
		</Comments>
		<Comments post_id="P5" user_id="B5" comment_id="C5">
			<Permbajtja>testi</Permbajtja>
			<Data_e_komentimit>27.09.2018</Data_e_komentimit>
			<Data_e_ndryshimit>13.01.2019</Data_e_ndryshimit>
		</Comments>
		<Comments post_id="P6" user_id="B1" comment_id="C6">
			<Permbajtja>testi</Permbajtja>
			<Data_e_komentimit>24.08.2018</Data_e_komentimit>
			<Data_e_ndryshimit>15.01.2019</Data_e_ndryshimit>
		</Comments>
		<Comments post_id="P7" user_id="B7" comment_id="C7">
			<Permbajtja>testi</Permbajtja>
			<Data_e_komentimit>01.08.2018</Data_e_komentimit>
			<Data_e_ndryshimit>15.01.2019</Data_e_ndryshimit>
		</Comments>
		<Comments post_id="P8" user_id="B5" comment_id="C8">
			<Permbajtja>testi</Permbajtja>
			<Data_e_komentimit>04.08.2018</Data_e_komentimit>
			<Data_e_ndryshimit>02.01.2019</Data_e_ndryshimit>
		</Comments>
		<Comments post_id="P9" user_id="B1" comment_id="C9">
			<Permbajtja>testi</Permbajtja>
			<Data_e_komentimit>08.08.2018</Data_e_komentimit>
			<Data_e_ndryshimit>17.01.2019</Data_e_ndryshimit>
		</Comments>
		<Comments post_id="P10" user_id="B2" comment_id="C10">
			<Permbajtja>testi</Permbajtja>
			<Data_e_komentimit>22.01.2018</Data_e_komentimit>
			<Data_e_ndryshimit>18.01.2019</Data_e_ndryshimit>
		</Comments>
		
		
		<Messages message_id="M1" user_id_to="B8" user_id_from="B4">
			<texti>Pershendetje</texti>
			<Data_e_dergimit>2016-09-04 01:00:00</Data_e_dergimit>
			<ora_e_leximit>2016-09-04 01:10:00</ora_e_leximit>
		</Messages>
		<Messages message_id="M2" user_id_to="B2" user_id_from="B5">
			<texti>A po mi qon detyrat e kimise.</texti>
			<Data_e_dergimit>2017-09-03 11:00:00</Data_e_dergimit>
			<ora_e_leximit>2017-09-03 11:05:02</ora_e_leximit>
		</Messages>
		<Messages message_id="M3" user_id_to="B1" user_id_from="B7">
